/** Static map of what metrics/data each provider sync handler pulls. */
export const PROVIDER_DATA_POINTS: Record<string, string[]> = {
  "Google Search Console": [
    "Impressions",
    "Clicks",
    "CTR",
    "Avg. Position",
    "Per-page Data",
  ],
  "Google Analytics 4": [
    "Sessions",
    "Users",
    "Bounce Rate",
    "Conversions",
    "Channels",
  ],
  "Google Ads": [
    "Campaigns",
    "Keywords",
    "Spend",
    "Quality Score",
    "Impression Share",
  ],
  "Meta Ads": ["Campaigns", "Spend", "ROAS", "Impressions", "Conversions"],
  "Google Business Profile": [
    "Reviews",
    "Ratings",
    "Listing Views",
    "Direction Requests",
  ],
  Instagram: ["Posts", "Followers", "Reach", "Engagement", "Stories"],
  "LinkedIn Page": [
    "Followers",
    "Post Impressions",
    "Engagement Rate",
    "Demographics",
  ],
  "YouTube Channel": [
    "Views",
    "Watch Time",
    "Subscribers",
    "Avg. View Duration",
  ],
  "Twitter/X": ["Followers", "Impressions", "Engagements", "Profile Visits"],
  "Google Tag Manager": ["Tags", "Triggers", "Variables"],
  "Google Analytics (UA)": ["Sessions", "Bounce Rate", "Goal Completions"],
  SEMrush: ["Keywords", "Backlinks", "Domain Authority", "Competitor Gap"],
  Ahrefs: ["Backlinks", "Referring Domains", "Organic Keywords", "DR Score"],
  Moz: ["Domain Authority", "Page Authority", "Spam Score", "Link Metrics"],
  "Screaming Frog": [
    "Crawl Errors",
    "Broken Links",
    "Meta Issues",
    "Page Speed",
  ],
  Hotjar: ["Heatmaps", "Session Recordings", "Funnel Drop-offs"],
  "Microsoft Clarity": [
    "Heatmaps",
    "Session Recordings",
    "Dead Clicks",
    "Rage Clicks",
  ],
  Salesforce: ["Leads", "Opportunities", "Pipeline Value", "Conversion Rate"],
  HubSpot: ["Contacts", "Deals", "Email Performance", "Lead Sources"],
  Slack: ["Alerts", "Report Digests", "Audit Notifications"],
  "WhatsApp Business": ["Message Delivery", "Read Rates", "Campaign Reach"],
  Razorpay: ["Payments", "Refunds", "Token Collections", "Success Rate"],
  Stripe: ["Charges", "Subscriptions", "Revenue", "Refunds"],
  "Zoho Books": ["Invoices", "Expenses", "P&L Reports"],
  Cloudflare: ["DNS Health", "CDN Cache Rate", "Threat Events", "Bandwidth"],
  "Anthropic Claude": [
    "Content Generations",
    "Brand Voice Score",
    "Copy Reviews",
  ],
};
